### ISSUE TITLE
Ruby missing ?!

### ISSUE THREAD

**Issue by luong-komorebi** [dgwozdz/HN_SO_analysis#1]
Hey there. Thanks for a nice analysis. I could see your mentioning ruby in the list of programming languages 

> The programming languages or technologies which were examined include: C, C++, C#, Cobol, CSS, D3.js, R, Delphi, Fortran, Hadoop, HTML, Java, Javascript, JQuery, Pascal, Perl, Python, PHP, Ruby, Rust, Scala, Shell, Spark, SQL, Swift, Tensorflow, VBA.  

But there arent any stats for Ruby at all. Am I missing something 🤔

**Comment by dgwozdz** [comment]
Hey! I only reported the plots I found interesting and Ruby was one of those languages for which I did not see a worth-reporting similarity. However, it was purely subjective decision (I did not have any quantitative criterion for this like in case of Granger causality test).
