### ISSUE TITLE
First graph used in JavaScript section references graphs from java

### ISSUE THREAD

**Issue by augbog** [dgwozdz/HN_SO_analysis#4]
Not sure if it's just a typo in the graph label but at the very end of the line, the JavaScript graphs mention Java. I also looked at them against the graphs in the Java section and they look the same but hard to say if they actually are. Feel free to close if not an issue.

<img width="937" alt="screen shot 2018-06-10 at 2 17 40 pm" src="https://user-images.githubusercontent.com/2054339/41206461-2e3c567a-6cb9-11e8-8896-b0c78ed309d4.png">

**Comment by dgwozdz** [comment]
It was an error, thanks for pointing this out. I updated the plot.

**Comment by augbog** [comment]
Great analysis btw :) love these types of things!
